comment:
  image:
    repository: apocatastasys/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: apocatastasys/post
    tag: latest
  service:
    externalPort: 5000

ui:
  image:
    repository: apocatastasys/ui
    tag: latest
  service:
    externalPort: 9292
